checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  external_code_coverage:
    timeout: 600

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
