name: "Continuous Integration"

on: [ push, pull_request ]

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install dependencies with composer
        run: composer install -ov

      - name: Run php-cs-fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --using-cache=no --verbose

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install dependencies with composer
        run: composer install -ov

      - name: Run vimeo/psalm
        run: ./vendor/bin/psalm --config=psalm.xml --shepherd

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install dependencies with composer
        run: composer install -ov

      - name: Run phpstan/phpstan
        run: ./vendor/bin/phpstan analyse src --level 7

  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    env:
      PHP_EXTENSIONS: dom, json, mbstring, curl, tokenizer
      PHP_INI_VALUES: assert.exception=1, zend.assertions=1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Override PHP ini values for JIT compiler
        run: echo "PHP_INI_VALUES::assert.exception=1, zend.assertions=1, opcache.enable=1, opcache.enable_cli=1, opcache.optimization_level=-1, opcache.jit=1255, opcache.jit_buffer_size=32M" >> $GITHUB_ENV

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress --prefer-lowest

      - name: Run tests with phpunit
        run: XDEBUG_MODE=coverage php ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.clover

      - name: Upload coverage file
        uses: actions/upload-artifact@v2
        with:
          name: phpunit.coverage
          path: coverage.clover

  upload_coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    needs: phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer

      - name: Download coverage files
        uses: actions/download-artifact@v2
        with:
          path: reports

      - name: Send code coverage report to Scrutinizer
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover ./reports/phpunit.coverage/coverage.clover